### ISSUE TITLE
Could not find a version that satisfies the requirement windows-curses

### ISSUE THREAD

**Issue by singularitti** [nitanmarcel/PipTUI#1]
When I am trying to install `PipTUI` with 
```shell
pipx install PipTUI
```
It throws out errors:
```shell
  ERROR: Could not find a version that satisfies the requirement windows-curses (from PipTUI) (from versions: none)
ERROR: No matching distribution found for windows-curses (from PipTUI)
'/Users/qz/.local/pipx/venvs/PipTUI/bin/python -m pip install PipTUI -q' failed
```
It seems to be a dependency-resolution problem.
I am using `pipx==0.13.0.1` with Python `3.7.4` on macOS 10.14.5.

**Comment by nitanmarcel** [comment]
Strange. Does it work with normal pip? The module it's in the pypi repository but if pipx uses a custom repository there's nothing I can do about it. 

https://pypi.org/project/windows-curses/

**Comment by nitanmarcel** [comment]
Oh, wait, I didn't read the MacOS line. It shouldn't add it to the requirements list. Let me check

**Comment by nitanmarcel** [comment]
@singularitti  It's fixed but before uploading it on pypi I want to know one thing.

I never used MacOS and since the script launches pip commands when a specific action is done (Installing, Uninstalling, etc) might not work with pipx.

Pipx is the only way to install python packages or there's also a pip on MacOS?

**Comment by singularitti** [comment]
Hi @nitanmarcel. There should be a `pip` on every system that Python supports. I should have explained, `pipx` is definitely not the only way to install a Python package on macOS. In fact, it is only used to install Python packages which provide executables, e.g., [`pylint`](https://www.pylint.org/#install), [`autopep8`](https://github.com/hhatto/autopep8), [`glances`](https://nicolargo.github.io/glances/), etc. See the [doc here](https://pipxproject.github.io/pipx/) if you are interested. Because the `PipTUI` seems to be an executable, so I first install it with `pipx`.  `pipx` creates virtualenv and install the executables to a certain place so that they could not be installed in my system directory. [Here](https://pipxproject.github.io/pipx/how-pipx-works/) is how it works (I recommend it, really).

**Comment by nitanmarcel** [comment]
Fixed in https://github.com/nitanmarcel/PipTUI/commit/0e8b64e3c706721e02bb1baaeb010c251e38ba7b

Because you're using pipx the app could not work if pip is not installed. A workaround for this would be setting up pip as an alias for  pipx.

Thanks!

**Comment by nitanmarcel** [comment]
> Hi @nitanmarcel. There should be a `pip` on every system that Python supports. I should have explained, `pipx` is definitely not the only way to install a Python package on macOS. In fact, it is only used to install Python packages which provide executables, e.g., [`pylint`](https://www.pylint.org/#install), [`autopep8`](https://github.com/hhatto/autopep8), [`glances`](https://nicolargo.github.io/glances/), etc. See the [doc here](https://pipxproject.github.io/pipx/) if you are interested. Because the `PipTUI` seems to be an executable, so I first install it with `pipx`. `pipx` creates virtualenv and install the executables to a certain place so that they could not be installed in my system directory. [Here](https://pipxproject.github.io/pipx/how-pipx-works/) is how it works (I recommend it, really).

Oh, so you're good to go :) I'll reopen the issue for a few hours if you have another problems :)

**Comment by singularitti** [comment]
I will try to install and report any problem that I meet.
