### ISSUE TITLE
Missing search shortcut

### ISSUE THREAD

**Issue by ccmorataya** [nitanmarcel/PipTUI#7]
I cant figure out how to search a package, reading the source code seems to not exist a shortcut for that.

**Comment by nitanmarcel** [comment]
Sorry for the late delay. GitHub has been wild on sending me notifications.

Under the packages you have a search box you can use

**Comment by ccmorataya** [comment]
@nitanmarcel thanks I see, but there isn't a shortcut for that

**Comment by nitanmarcel** [comment]
> @nitanmarcel thanks I see, but there isn't a shortcut for that

Added a search shortcut in https://github.com/nitanmarcel/PipTUI/commit/87c1a6f82bd8178bf24e8a787f745231d5a8244f
